spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo?createDatabaseIfNotExist=true
    username: root
    password: Lmlyraa200kh!

  jpa:
    show-sql: true

server:
  port: 8080

# STEP 2: JWT Configuration
# These properties control how our JWT tokens are created and validated
jwt:
  # Secret key used to sign JWT tokens - MUST be kept secret in production
  # In production, use environment variables or secure vault instead of hardcoding
  # This key should be at least 256 bits (32 characters) for HS256 algorithm
  secret: mySecretKeyForJwtTokenGenerationAndValidationMustBeLongEnough123456
  # Token expiration time in milliseconds (86400000 ms = 24 hours)
  # After this time, the token becomes invalid and user must login again
  expiration: 86400000